<!DOCTYPE html>
<html>
<head>
    <title>Error</title>
</head>
<body>
    <p>Lo sentimos, no hemos podido establecer una conexión con el microservicio. Por favor, inténtelo de nuevo más tarde.</p>
</body>
</html>

